language: node_js
node_js:
  - "6"
  - "5"
  - "4.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm i -g mocha
after_script:
  - codeclimate-test-reporter < lcov.info